name: IPC_FTP_KX

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ftptest/qwe123!@#
    - name: IPC_FTP_KX
      run: docker build . --file fauria/vsftpd --tag IPC_FTP_KX:$(date +%s)
